[package]
name = "cell"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
memmap2 = "0.9"
rand = "0.8"
anyhow = "1"
wasmtime = "28.0"
regex = "1.11"

[lib]
crate-type = ["cdylib"]
